Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
import numpy as np

# Define the list with correct quotation marks
list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from the list
array_list = np.array(list_)

# Print the data type of the list_
print("Data type of list_:", type(list_[0]))

# Print the data type of the array_list
print("Data type of array_list:", array_list.dtype)




Data type of list_: <class 'str'>
Data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [1]:
import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array
array_list = np.array(list_)

# Print the data type of each element in the list
print("Data type of elements in list_:")
for item in list_:
    print(type(item))

# Print the data type of elements in the NumPy array
print("\nData type of elements in array_list:")
print(array_list.dtype)


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(array_list.dtype)  # This will print 'U1' indicating Unicode strings of length 1

array_list = np.array(object=list_, dtype=int)
print(array_list.dtype)  # This will print 'int64' indicating 64-bit integers

# For the original list_
for element in list_:
    print(type(element))

# For the modified array_list
for element in array_list:
    print(type(element))

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print(num_array.dtype)  # This will print 'int64' indicating 64-bit integers


<U1
int32
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
int32


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [3]:
import numpy as np

# Given array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape of the array
print("Shape of num_array:", num_array.shape)

# (ii) Size of the array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [4]:
import numpy as np

# Create a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the created matrix
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [5]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the created identity matrix
print(identity_matrix)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
